### ISSUE TITLE
How to train different data sets？

### ISSUE THREAD

**Issue by maxadda** [wvangansbeke/LaneDetection_End2End#11]
Hi,
Thank you very much for your meaningful work. I've probably reproduced the results of your paper, so I want to extend this work to different data sets.
so I need your help: 
How to generate the parameters of 'poly_params' and 'position'?
 I made them differently from what you provided. Would you give me a detailed description?

**Comment by wvangansbeke** [comment]
Hi @maxadda,

To generate the lane line coefficients, you need to perform similar calculations as the fitting module in the network. Here you need to transform the lane line coordinates, provided by tusimple, using the homography matrix to a birds eye view. Then, you can fit a second degree polynomial through those transformed coordinates. The parameters are the ground truth values for the final regression. 

I annotated the position of the car myself. For this, I used the same ordering as tusimple. 

Hope this helps, 
Wouter

**Comment by maxadda** [comment]
Hi @wvangansbeke ,

I follow the instructions above to write a Python script but the label is still different. Would you share the script that generates the label?

**Comment by wvangansbeke** [comment]
Hi @maxadda,

Are you getting incorrect results or are they slightly different? Make sure you don't transform all points with the homography matrix since you shouldn't use points above a certain height. They will be mapped to close to infinity.

Also, some images in ground truth files of tusimple have a different/incorrect lane line order.

Sharing my code for these computations would require a lot of cleanup, so I'm not sure when this will happen.

Kind regards, 
Wouter

**Comment by maxadda** [comment]
Hi @wvangansbeke ，

This is my processing code. Could you give me some advice?

import json
import numpy as np
import cv2

def homogenous_transformation(x,y):
    """
    Helper function to transform coordionates defined by transformation matrix
    
    Args:
            Matrix (multi dim - array): Transformation matrix
            x (array): original x coordinates
            y (array): original y coordinates
    """
    y_start = 0.3
    y_stop = 1
    src = np.float32([[0.45,y_start],[0.55, y_start],[0.1,y_stop],[0.9, y_stop]])
    dst = np.float32([[0.45, y_start],[0.55, y_start],[0.45, y_stop],[0.55,y_stop]])
    M = cv2.getPerspectiveTransform(src, dst)
    
    ones = np.ones((1,len(y)))
    coordinates = np.vstack((x, y, ones))
    trans = np.matmul(M, coordinates)
            
    x_vals = trans[0,:]/trans[2,:]
    y_vals = trans[1,:]/trans[2,:]
    return x_vals, y_vals

labels_file1 = [json.loads(line) for line in open("Curve_parameters.json").readlines()]

x = np.array(labels_file1[0]['lanes'][0])
y = np.array(labels_file1[0]['h_samples'])
print ("poly_param:",labels_file1[0]['poly_params'][0])
index = []
for i in range(len(x)):
    if x[i] < 0:
         index.append(i)
new_x = np.delete(x,index)
new_y = np.delete(y,index)

new_x = new_x / 1279.
new_y = (new_y - 80) / 639.
x_val , y_val = homogenous_transformation(new_x,new_y)
z1 = np.polyfit(y_val,x_val,2)
print(z1)

**Comment by wvangansbeke** [comment]
Hi @maxadda,

At first glance, you should not include points that lie too high, i.e. much higher than the points used for the homogeneous transformation matrix. The rest seems good. 

Maybe try to plot the lines on the images in birds eye view. It will make it easier.

Kind regards, 
Wouter

**Comment by jiaofang1222** [comment]
> Hi @wvangansbeke ，
> 
> This is my processing code. Could you give me some advice?
> 
> import json
> import numpy as np
> import cv2
> 
> def homogenous_transformation(x,y):
> """
> Helper function to transform coordionates defined by transformation matrix
> 
> ```
> Args:
>         Matrix (multi dim - array): Transformation matrix
>         x (array): original x coordinates
>         y (array): original y coordinates
> """
> y_start = 0.3
> y_stop = 1
> src = np.float32([[0.45,y_start],[0.55, y_start],[0.1,y_stop],[0.9, y_stop]])
> dst = np.float32([[0.45, y_start],[0.55, y_start],[0.45, y_stop],[0.55,y_stop]])
> M = cv2.getPerspectiveTransform(src, dst)
> 
> ones = np.ones((1,len(y)))
> coordinates = np.vstack((x, y, ones))
> trans = np.matmul(M, coordinates)
>         
> x_vals = trans[0,:]/trans[2,:]
> y_vals = trans[1,:]/trans[2,:]
> return x_vals, y_vals
> ```
> 
> labels_file1 = [json.loads(line) for line in open("Curve_parameters.json").readlines()]
> 
> x = np.array(labels_file1[0]['lanes'][0])
> y = np.array(labels_file1[0]['h_samples'])
> print ("poly_param:",labels_file1[0]['poly_params'][0])
> index = []
> for i in range(len(x)):
> if x[i] < 0:
> index.append(i)
> new_x = np.delete(x,index)
> new_y = np.delete(y,index)
> 
> new_x = new_x / 1279.
> new_y = (new_y - 80) / 639.
> x_val , y_val = homogenous_transformation(new_x,new_y)
> z1 = np.polyfit(y_val,x_val,2)
> print(z1)

When I use my own data, there is no ground truth coordinates of the lane lines.How should I get the curve parameters or how to get ground truth coordinates of the lane lines?How should I choose homography matrix？Looking forward to your reply.

**Comment by TonightGo** [comment]
Hi

> Hi @wvangansbeke ，
> 
> This is my processing code. Could you give me some advice?
> 
> import json
> import numpy as np
> import cv2
> 
> def homogenous_transformation(x,y):
> """
> Helper function to transform coordionates defined by transformation matrix
> 
> ```
> Args:
>         Matrix (multi dim - array): Transformation matrix
>         x (array): original x coordinates
>         y (array): original y coordinates
> """
> y_start = 0.3
> y_stop = 1
> src = np.float32([[0.45,y_start],[0.55, y_start],[0.1,y_stop],[0.9, y_stop]])
> dst = np.float32([[0.45, y_start],[0.55, y_start],[0.45, y_stop],[0.55,y_stop]])
> M = cv2.getPerspectiveTransform(src, dst)
> 
> ones = np.ones((1,len(y)))
> coordinates = np.vstack((x, y, ones))
> trans = np.matmul(M, coordinates)
>         
> x_vals = trans[0,:]/trans[2,:]
> y_vals = trans[1,:]/trans[2,:]
> return x_vals, y_vals
> ```
> 
> labels_file1 = [json.loads(line) for line in open("Curve_parameters.json").readlines()]
> 
> x = np.array(labels_file1[0]['lanes'][0])
> y = np.array(labels_file1[0]['h_samples'])
> print ("poly_param:",labels_file1[0]['poly_params'][0])
> index = []
> for i in range(len(x)):
> if x[i] < 0:
> index.append(i)
> new_x = np.delete(x,index)
> new_y = np.delete(y,index)
> 
> new_x = new_x / 1279.
> new_y = (new_y - 80) / 639.
> x_val , y_val = homogenous_transformation(new_x,new_y)
> z1 = np.polyfit(y_val,x_val,2)
> print(z1)

Hi @maxadda @wvangansbeke @jiaofang1222 ,

What does the following code mean?
"> new_x = new_x / 1279.
> new_y = (new_y - 80) / 639."

using this code can't get right result. So I modify the code "> z1 = np.polyfit(y_val,x_val,2)" to "> z1 = np.polyfit(1-y_val,x_val,2)", the result as follows:
my result: -0.001093312092431737,   0.14495017836454557,   0.33690583787800615
gt_param: -0.0010622867390580224, 0.14236825172981402,   0.33713653071570787

Could I use this label to train the model on other datasets?

Best regards,
Ice

**Comment by jeannotes** [comment]
I'm sorry . when will you release you code

**Comment by wvangansbeke** [comment]
Hi @jeannotes ,

Actually you can still find the latest version in the commit history [here](https://github.com/wvangansbeke/LaneDetection_End2End/tree/5f3bf44a57a4e020b6829c9989104dd2178a74b5).

Kind regards,
Wouter
