### ISSUE TITLE
Single Image Inference

### ISSUE THREAD

**Issue by Jeremy26** [wvangansbeke/LaneDetection_End2End#12]
Hello,

I am trying to perform inference in a single image as well. 

Here's what I got; it's not working yet.

```
### Open Image
from PIL import Image
image = Image.open("10.jpg")

 ### 1 : Load the Model
model = Net(args)
checkpoint = torch.load("model.pth.tar")
model.load_state_dict(checkpoint['state_dict'])


### 2 : Preprocessing / Transformations
w,h = image.size
totensor = transforms.ToTensor()
resize = args.resize ### 256
image = F.crop(image, h-640, 0, 640, w)
image = F.resize(image, size=(resize, 2*resize), interpolation=Image.BILINEAR)
image = totensor(image).float()

## Pass it to the model
with torch.no_grad():
        beta0, beta1, beta2, beta3, weightmap_zeros, M, output_net, outputs_line, outputs_hozizon = model(image, True)
 ### I also tried = model.forward(image, True)
```

And I have an error : 
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [13, 3, 3, 3], but got 3-dimensional input of size [3, 256, 512] instead

The pipeline should be usable by anyone who wants to test once fixed. Can anybody help ?

**Comment by Jeremy26** [comment]
Hello,

I added these two lines before calling the model (before with torch.no_grad())
    image = image.cuda()
    image = image[None,:, :, :]
Seems to work, I will plot the lines to get confirmation

**Comment by huang45** [comment]
Hi @Jeremy26 , how about the result? How do you define the args? I tried this but don't know how to define it without using parser.
By the way, maybe we can reuse the code of save_weightmap for single image inference.
```
                save_weightmap('test', M, M_inv,
                               weightmap_zeros, beta0, beta1, beta2, beta3,
                               gt0, gt1, gt2, gt3, line_pred, gt, 0, i, input,
                               args.no_ortho, args.resize, args.save_path)
```

**Comment by Jeremy26** [comment]
![result](https://user-images.githubusercontent.com/11992338/58475149-795b4400-814d-11e9-81d8-68a41bfe59dd.png)

Result so far

I have used the code from validate for the inference and from utils.draw_fitted_line then

**Comment by Jeremy26** [comment]
args are defined using parser when you call the script; for inference, you can define them as non required.
It can all be configured in utils file

**Comment by Jeremy26** [comment]
Also, I am not sure about my training; it seems like the best epoch was 234 (out of 350)

Here is my last iteration
 => Start train set for EPOCH 350
253it [01:04,  3.99it/s]
63it [00:08,  7.25it/s]
===> Average AREA**2-loss on training set is 0.00000119
===> Average AREA**2-loss on validation set is 0.00001938
===> Average exact area on training set is 0.00085674
===> Average exact area on validation set is 0.00146263
===> Last best AREA**2-loss was 0.00145391 in epoch 235

How to interpret this ?

**Comment by huang45** [comment]
I found that when we set end to end mode false, the best model was saved automatically. But it seems there are some bugs when we set it true, the best mode was not saved. @Jeremy26

**Comment by wvangansbeke** [comment]
Hi @huang45,

You're correct. I could happen that the best model is not saved for those specific settings. I will fix it.

Kind regards

**Comment by ryan1051** [comment]
@Jeremy26  Hi, do you get the right inference result? And can you show me your inference project?
Thank you.

**Comment by Jeremy26** [comment]
@ryan1051 No I didn't arrive to the result. Also when I tried to run it, I had almost 500ms for a single image, resulting at 2 FPS (on GTX 1070) which wasn't really what I expected

**Comment by heethesh** [comment]
@Jeremy26 did you try running it for multiple images and note the results? Usually the first inference takes much longer (x20 at times) than subsequent inferences.

**Comment by Jeremy26** [comment]
@heethesh Might try that, thanks! Also, do you know about how to get the correct lines and not what I showed in the previous picture ?

**Comment by prolulu** [comment]
@Jeremy26  @wvangansbeke  @huang45 @ryan1051 
I use Jeremy‘s code, but I don't know what F is. So I use opencv to resize images.
And I meet a error that

`RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

This is my code:

```
import torch
from PIL import Image
import cv2
import imageio
image = imageio.imread("10.jpeg")

model = torch.load("model_best_epoch_204.pth.tar",map_location="cpu")
#model = torch.load("model_best_epoch_204.pth.tar")  using this line will report the same error.

from Networks.LSQ_layer import Net
from Networks.utils import define_args
global args

parser = define_args()

args = parser.parse_known_args()[0]  

print(args.resize)
image = cv2.resize(image,(args.resize*2,args.resize),interpolation=Image.BILINEAR)

model = Net(args)
from torchvision import transforms

totensor = transforms.ToTensor()

image = totensor(image).float()

image = image[None,:,:,:]

image = image.cuda()
print(type(image))

print(image.shape)

with torch.no_grad():
    beta0, beta1, beta2, beta3, weightmap_zeros, M, output_net, outputs_line, outputs_hozizon = model(image, True)

```

**Comment by wvangansbeke** [comment]
Hi @prolulu,

Make sure to put the model on the GPU as in the original [code](https://github.com/wvangansbeke/LaneDetection_End2End/blob/master/Birds_Eye_View_Loss/main.py#L79). In your case, the inputs are located on the GPU and the weights of the model on the CPU. This will indeed result in a runtime error.

Best,
Wouter

**Comment by prolulu** [comment]
Hi @wvangansbeke 
Do you mean using 
`model = torch.load("model_best_epoch_204.pth.tar",map_location=lambda storage, loc: storage.cuda(1))`
I try it just recently, BUT the same error is reported. 😢 

Best,
Lulu

**Comment by wvangansbeke** [comment]
Can you try:
`device = torch.device('cuda')`
`model = torch.load("model_best_epoch_204.pth.tar",map_location=device)`

or 

`model = torch.load("model_best_epoch_204.pth.tar")
`model.cuda()`

Best.

**Comment by prolulu** [comment]
Successfully!
By adding
`model = model.cuda()`

The code seems to run and output some data.
But I don't know how can I show the results on pics,I will do it subsequently.

Thank you very much!Wouter :smile:

**Comment by circlesun** [comment]
I have solved it!!! Thanks to Jeremy26

**Comment by china56321** [comment]
> I have solved it!!! Thanks to Jeremy26
> ![Screenshot from 2020-03-15 12-37-55](https://user-images.githubusercontent.com/43404344/76821313-9120c780-6848-11ea-89eb-6eaa9506428d.png)
> it looks like this.Then I transform it to another scale.

Could you publish you test code ?

**Comment by JunjieLiuSWU** [comment]
> I have solved it!!! Thanks to Jeremy26
> ![Screenshot from 2020-03-15 12-37-55](https://user-images.githubusercontent.com/43404344/76821313-9120c780-6848-11ea-89eb-6eaa9506428d.png)
> it looks like this.Then I transform it to another scale.

Hello, Can you share us how you get the correct result?

**Comment by foxkw** [comment]
> I have solved it!!! Thanks to Jeremy26
> ![Screenshot from 2020-03-15 12-37-55](https://user-images.githubusercontent.com/43404344/76821313-9120c780-6848-11ea-89eb-6eaa9506428d.png)
> it looks like this.Then I transform it to another scale.

People like you have destroyed the ecological environment of open source. Enjoy other people's ideas but don't share them with others

**Comment by JunjieLiuSWU** [comment]
![Uploading new_output.png…]()
There are the test file [https://github.com/JunjieLiuSWU/LaneDetection_End2End](https://github.com/JunjieLiuSWU/LaneDetection_End2End)

**Comment by JunjieLiuSWU** [comment]
There are the test file [https://github.com/JunjieLiuSWU/LaneDetection_End2End](https://github.com/JunjieLiuSWU/LaneDetection_End2End)
![new_output](https://user-images.githubusercontent.com/50912231/115118096-3cfc8f80-9fd4-11eb-8de6-a9fa72172ec4.png)
