### ISSUE TITLE
Sorry,excuse me,when will the code be released?

### ISSUE THREAD

**Issue by PenghuahuaPeng** [wvangansbeke/LaneDetection_End2End#2]

**Comment by wvangansbeke** [comment]
Thank you for your interest! I'm currently cleaning up the code. This shouldn't take too long.

**Comment by PenghuahuaPeng** [comment]
Thanks for your work!

**Comment by soulmeetliang** [comment]
Thanks！

**Comment by MistreanuIonutCosmin** [comment]
Hi @wvangansbeke and thank you for your work!
Can you give us an update of the current status?

**Comment by wvangansbeke** [comment]
I'm just waiting on KU Leuven (for licence reasons). I hope this will happen by next week.

**Comment by hellosher** [comment]
Sorry,@wvangansbeke ,I want to ask that when the code will be release,or Can you provide some other materials?

**Comment by yongjingli** [comment]
Hi, I am very interested in the code, it would be nice if the code will be release in soon. @wvangansbeke

**Comment by HyperPotatoNeo** [comment]
We have tried an implementation of the paper but aren't getting good results(Probably got something wrong). It would really help us if the code can be released soon, as we are interested in adopting the method for our model.
