### ISSUE TITLE
I want to actually use this model in my DIY self driving car

### ISSUE THREAD

**Issue by zorrobyte** [wvangansbeke/LaneDetection_End2End#28]
Hello,

I'm a hobbiest software dev who has only gotten into ML topics. OpenPilot is an open source project to add L2 autonomy to most cars 2017 and newer. The code repo is here:
https://github.com/commaai/openpilot

The community is currently constrained to Qualcomm based hardware due to the provided models being in a snpe dlc format. I instead bought a Nvidia Jetson Nano and many others are working on custom hardware solutions.

I realize that you are in academia and your intents are to further the field, so this may be out of your scope. But..

It would be fantastic if I could use this model in a real world application. The outputs from a model would be consumed here (which are used by Pathplanner/MPC to generate desired steering angles) https://github.com/commaai/openpilot/blob/devel/selfdrive/controls/lib/model_parser.py

An example of output from the existing model is here (check model file):
https://www.dropbox.com/sh/7ncns9yuk7lx910/AADWlF2y9nple5in6YXtv06ba?dl=0

We can ignore path, lead as they aren't currently used. Only left, right lane is important (I think).
An example:
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/7257172/61023753-31992080-a379-11e9-9dee-0da5be2b85d1.png">

I see that the existing model outputs are contained in the lane object, just the scale is wrong for this use case it seems.

It would mean a great deal to many users of OpenPilot to have an alternative model to use. One community member has offered $5,000 USD for a workable solution (we are rather passionate users).

I'm training a model now using your codebase and will continue tinkering to see if I can get something workable for OpenPilot. I am only a novice, so any assistance you could provide would be wonderful (although, I have no expectations).

Regardless, thank you for sharing your work!

Update: The 0.6 model puts out polys instead of X Y. I also have a network architecture diagram of their existing network (it's all OSS, just in dlc format that is unfriendly). I can collect any information you'd request if you'd take this on.
![lqbEHvlnQHi7OpiejmgdAA_thumb_2595](https://user-images.githubusercontent.com/7257172/61067888-af3f4980-a3d6-11e9-9cc6-b29957d23b66.jpg)

https://youtu.be/IXGizNFUFyI

**Comment by zorrobyte** [comment]
I'm going to go ahead and close this, as it's not directly relevant to your project. PM me if you find interest.

**Comment by wvangansbeke** [comment]
Hi @zorrobyte,

This is actually pretty interesting. I might take a look at it. I don't have a lot of time at the moment but will hit you up when I have.

Best,
Wouter

**Comment by zorrobyte** [comment]
Sounds great, Dr. Wouter!

@mention me again when you get some free time - I'm always available. 

Ross

**Comment by zorrobyte** [comment]
Here is a dump of their existing model graph:
https://www.dropbox.com/s/czwclv5uetcyg5y/driving_model.html?dl=0
