### ISSUE TITLE
lables/label_new.json

### ISSUE THREAD

**Issue by fenling** [wvangansbeke/LaneDetection_End2End#29]
hi wvangansbeke:
      I have some questions about "label_new.json"
      label_new.json
      {"position": [0, 0, 1, 1, 1, 1, 1, 0], "lines": [-1, -1, 1, 0, 0, 0, 0, 1, -1, -1], "raw_file": "clips/0313-1/6040/20.jpg"} 
     in the  Curve_parameters.json
   "lanes": [[-2, -2,...,307, 299],[-2, -2,...,1250, 1265, -2, -2, -2, -2, -2],[-2, -2,...,241, 212,...-2, -2],[-2, -2,...,1229, 1269,...-2, -2], "raw_file": "clips/0313-1/6040/20.jpg", "run_time": 20, "poly_params": [[-0.00074, 0.0480, 0.466], [-0.000110, -0.020, 0.569], [-0.00282, 0.127, 0.3673],  [0.00101, -0.10, 0.69]]}
    question1:how to get the position [0, 0, 1, 1, 1, 1, 1, 0],
    question2:how to get the lines": [-1, -1, 1, 0, 0, 0, 0, 1, -1, -1],     
in the prediscuss I found "A 1 means the line is a continuous line, a 0 means it is a dashed line and a -1 means the line is not present. The latter is really important, because the network will always output 2 or 4 lane lines." but  i still can not get the right mean.

**Comment by wvangansbeke** [comment]
Hi @fenling,

The annotations are made relative to the car. Lets take the lines for example. The car is positioned between the 5th and 6th value (in the middle of the array). So there is a maximum of 5 different lines on each side of the car for an array with 10 values.

Best,
Wouter

**Comment by fenling** [comment]
hi Wouter:
clips/0313-1/6040/20.jpg groundtruth has four lines，
lines": [-1, -1, 1, 0, 0, 0, 0, 1, -1, -1], it means 4 dashed line , 2  continuous line,why the lines has 6 lines.
and how to generate"position [0, 0, 1, 1, 1, 1, 1, 0]“

**Comment by wvangansbeke** [comment]
Hi @fenling,

You're correct. I sometimes annotated more lines than the original TuSimple ground truth. 

I generated the array called 'position' also relative to the egolane of the car. It tells you how many lanes are on the left and the right side of the car. The example shows that there are 2 lanes on the left and 3 lanes on the right side of the car (assigned with a 1 in the array). Remember: the car is positioned in the middle of the array.

Best,
Wouter
