### ISSUE TITLE
Tu simple evaluation resizing

### ISSUE THREAD

**Issue by Msabih** [wvangansbeke/LaneDetection_End2End#33]
Hi,

The tusimple evaluation takes as input h samples and lane points with the size of 720 x 1280 however if we train a network on smaller size then there are two ways to go about it. 

a) resize the network output image to 720 x 1280.

b) resize the points to smaller size and generate y samples/lane points pair.

Which one do you think is best and if this is considered in your code ?

**Comment by wvangansbeke** [comment]
Hi @Msabih,

I resized both the image and rescaled the points to match the input size. For the input size I cropped the upper part and resized to an aspect ratio of (256, 512). 

For testing I scaled up the coordinates. When my code is back online, just take a look at the dataloader which should be fairly simple to understand. 

Best,
Wouter

**Comment by Msabih** [comment]
@wvangansbeke

So does by cropping you mean that you throw away the non lane part of the image and use only the lane part of the image ? I was resizing the whole image.

May be after cropping, I will be loosing leas information in the lane part of the image

**Comment by wvangansbeke** [comment]
@Msabih,

Yeah. You need to resize after cropping.
