### ISSUE TITLE
When will the code get back? 

### ISSUE THREAD

**Issue by kevinsu628** [wvangansbeke/LaneDetection_End2End#38]
Hi, I am wondering when the license issue can be fixed so that we can check out the code. 
Thanks!

**Comment by wvangansbeke** [comment]
Hi @kevinsu628,

Actually you can still find the latest version in the commit history [here](https://github.com/wvangansbeke/LaneDetection_End2End/tree/5f3bf44a57a4e020b6829c9989104dd2178a74b5).

I will put it back online this week.

Kind regards,
Wouter

**Comment by noobliang** [comment]
> Hi @kevinsu628,
> 
> Actually you can still find the latest version in the commit history [here](https://github.com/wvangansbeke/LaneDetection_End2End/tree/5f3bf44a57a4e020b6829c9989104dd2178a74b5).
> 
> I will put it back online this week.
> 
> Kind regards,
> Wouter



> Hi, I am wondering when the license issue can be fixed so that we can check out the code.
> Thanks!



> Hi @kevinsu628,
> 
> Actually you can still find the latest version in the commit history [here](https://github.com/wvangansbeke/LaneDetection_End2End/tree/5f3bf44a57a4e020b6829c9989104dd2178a74b5).
> 
> I will put it back online this week.
> 
> Kind regards,
> Wouter

Hi, please  put code back  , please .   thanks a  million .

**Comment by YoungGer** [comment]
want the code be back, too. thanks a million.

**Comment by wvangansbeke** [comment]
Hey guys,

You can still find the previous version in the commit history [here](https://github.com/wvangansbeke/LaneDetection_End2End/tree/5f3bf44a57a4e020b6829c9989104dd2178a74b5).

I made some additions and improved the README but I'm still waiting on a response from the legal team before I can share it. Can't take too much longer.

Kind regards,
Wouter
