### ISSUE TITLE
How to visualize the model？how to open the file of .pth.tar?

### ISSUE THREAD

**Issue by xxzcxb1314** [wvangansbeke/LaneDetection_End2End#39]

**Comment by wvangansbeke** [comment]
Hi @xxzcxb1314 ,

You can load this file using Pytorch's framework: See the doc for `torch.load` on their website.

Kind regards, 
Wouter

**Comment by xxzcxb1314** [comment]
Thank you for  your reply.I will have a try.



---Original---
