### ISSUE TITLE
How to find the number of lanes?

### ISSUE THREAD

**Issue by sdantuluri-renovo** [wvangansbeke/LaneDetection_End2End#40]
Hey there, is there a way to find the number of lanes? I understand that there is a max of 4 lanes that the model can detect, but is there a way to find the number of lanes?

**Comment by wvangansbeke** [comment]
Hi @sdantuluri-renovo,

You could learn a _stopping criterium_ in order to know when there are no more lane lines present in the image. This technique is used in some instance segmentation methods. Maybe take a look at those.

Kind regards,
Wouter
