### ISSUE TITLE
end to end train

### ISSUE THREAD

**Issue by mjanddy** [wvangansbeke/LaneDetection_End2End#45]
hi,   Is  the end2end   suitable for unclassified lanes?

**Comment by wvangansbeke** [comment]
Hi @mjanddy,

We rely on a consistent ordering of the lane lines to train the network correctly. You can combine our least squares module with an instance segmentation approach if you don't want to rely on this specific order.

Best,
Wouter

**Comment by wvangansbeke** [comment]
Feel free to reopen if something is unclear.
