### ISSUE TITLE
How to get image output 

### ISSUE THREAD

**Issue by MHN-II** [wvangansbeke/LaneDetection_End2End#46]
Hey Wouter, 
After completing the training using 
`python main.py --image_dir /path/to/image/folder --gt_dir /path/to/ground_truth/folder --end_to_end True` 
How can do you use the weights to evaluate the model on images to get outputs similar to the ones in the readme ? 

ie: 
![image](https://user-images.githubusercontent.com/24802401/66416384-b07b1500-e9cb-11e9-8ff5-f3d7f4eef1a3.png)

**Comment by wvangansbeke** [comment]
Hey MHN-II,

You can simply load the weights of the trained network using `torch.load`. The network will predict the coefficient of the polynomial for each lane line. Opencv was used to visualize these curves. Take a look the function `cv2.polylines` or `cv2.circle`. This allows you draw the lane lines as in the figure. This should be fairly straightforward. 

Best, 
Wouter
