### ISSUE TITLE
How to train another dataset of multi-lane

### ISSUE THREAD

**Issue by Judyhero** [wvangansbeke/LaneDetection_End2End#47]
If I train this network with another dataset, how to prepare the dataset and the code for training should be modified?

thanks.

**Comment by Judyhero** [comment]
Besides, does the ground truth image is the binary image of lane lines?

**Comment by wvangansbeke** [comment]
Hi @Judyhero,

- To train on another dataset you'll need the ground truth coordinates for each lane line. You need to make sure that the order of the lane lines in the ground truth is fixed and relative to the car. With this information you can compute the json files in the Dataset folder by fitting a polynomial through these ground truth coordinates. 

- The segmentation ground truth is an image which contains a label for each pixel of the lane line. So, all the pixels of the same line contain the same label. If you want to detect 4 lane lines, the values range from 1 to 4 (zero will denote the background) to distinguish each instance.

Best,
Wouter

**Comment by Judyhero** [comment]
Thanks for your reply, 

Is the polynomial fitting performed on birds` eye view ?

And what is usage of "label_new.json" in the "Labels" file ?

**Comment by wvangansbeke** [comment]
Hey,

- Indeed, I do the regression towards the coefficients of the polynomial in bird's eye view. 

- The json file contains the ground truth for the position of the car and the type of the line. 

Best, 
Wouter

**Comment by Judyhero** [comment]
Very thanks for your patient reply,

In "label_new.json", such as "position": [0, 0, 1, 1, 1, 1, 1, 0], "lines": [-1, -1, 1, 0, 0, 0, 0, 1, -1, -1]

What is the meaning of 0, 1, -1 ?

How those numbers in "position" and "lines" represent the position of the car and the type of the line?

**Comment by wvangansbeke** [comment]
Hey @Judyhero,

For the positions: a 0 means that there is no lane in the image. A 1 means that there is.  For the lines: a -1 indicates that there is not line present, a 0 says it is a dashed line and a 1 says it is a solid line. 
Every array is always computed relative to the car. Imagine that the car is positioned between the fourth and fifth element of the positions array. This tells you that there are 2 lanes on the left of the car and three lanes on the right in the example. 

Maybe also check this #29 issue. 

Best,
Wouter

**Comment by Judyhero** [comment]
Very thanks for your patient reply,

As for the recorded road images without any car, what should the "position" array be ?

In "lanes_ordered.json", what the usage of " "run_time": 20 " at the end of each line?

Since the curve parameters are calculated on bird's eye view, does the bird's eye view transformation is needed in training or testing process ?
