### ISSUE TITLE
How can I get the testset dataset?

### ISSUE THREAD

**Issue by hitczr** [wvangansbeke/LaneDetection_End2End#49]
Hello:
    The dataset you provide in the link include 2664 images rather than 3626images. Where can I download the latest dataset?
    By the way, when you do  training in BackProjection_Loss, you set clas = 1 so it needs the test images, how can  I get it and its' json file? 
    I set clas=0 so that the training can continue, but the training record has something wrong although it doesn't matter.
Best regards
Max

**Comment by wvangansbeke** [comment]
Hi @hitczr,

You can find the link the dataset and the json files in the REAMDE. For the _backprojection_ part, l indeed used the complete TuSimple dataset.

Best,
Wouter
