### ISSUE TITLE
python main.py

### ISSUE THREAD

**Issue by xxzcpsmemeda** [wvangansbeke/LaneDetection_End2End#53]
python main.py --image_dir ./Labels/images/ --gt_dir ./Labels/ground_truth/ --end_to_end True
size train loader is 2901
size valid loader is 725
Traceback (most recent call last):
  File "main.py", line 548, in <module>
    main()
  File "main.py", line 89, in main
    split_percentage=args.split_percentage)
  File "/home/chengpeisong/Downloads/LaneDetection_End2End-master/Backprojection_Loss/Dataloader/Load_Data_new.py", line 277, in get_loader
    nclasses=nclasses)
  File "/home/chengpeisong/Downloads/LaneDetection_End2End-master/Backprojection_Loss/Dataloader/Load_Data_new.py", line 92, in __init__
    assert len(self.rgb_lst) == len(self.gt_lst) == 3626
AssertionError

How to solve it ?The image_dir is  the folder images of dir, right?

**Comment by wvangansbeke** [comment]
Hi @xxzcpsmemeda, 

The code for the backprojection loss works on the complete TuSimple dataset (=3626 images). The link is in the README.

Best,
Wouter

**Comment by oesni** [comment]
So, Do I need to create ground truth png images for complete TuSimple dataset(=3626 images)??
Your link contains only 2535 jpg images and 2535 ground truth png images.

**Comment by wvangansbeke** [comment]
Hi @oesni,

Yes. For the conventional semantic segmentation approach you'll need the ground truth maps. It's very easy to make them though. I only included the ground truth for the egolane experiments. 

Best, Wouter

**Comment by JZlearnCode** [comment]
Hello, Thank you for the awesome repo! May I get some help on how to run the main.py when "args.end_to_end" is set to "True"?

I'm trying to run main.py, but "Backprojection_Loss/Loss_crit.py" reported error at the line"diff = params.squeeze(-1) - gt_params". Maybe I wasn't using the correct inputs and json files. 

The error message says "RuntimeError: The size of tensor a (3) must match the size of tensor b (56) at non-singleton dimension 1". 
I printed out their sizes. The size for "params.squeeze(-1)" is 8 x 3, the size for "gt_params" is 8 x 56. 

Thanks a lot!

**Comment by kingtaewoo** [comment]
@oesni 안녕하세요, 혹시 python main.py --image_dir ./Labels/images/ --gt_dir ./Labels/ground_truth/ --end_to_end True 이것을 어떤 곳에 어떻게 입력하셨는지 궁금합니다. 

어떤 방식으로 실행하는지 현재 이것저것 오픈소스 통해서 공부중인데 혼란이 많아서요.  좀 도와주시면 감사하겠습니다.
