### ISSUE TITLE
test in an image or a video

### ISSUE THREAD

**Issue by wilxy** [wvangansbeke/LaneDetection_End2End#54]
Hi Wouter,
  I used main.py to get a model already. 
  How can I use this model and your code to test in an image or a video?

Greetings,
Wilxy

**Comment by wilxy** [comment]
I used Birds_Eye_View_Loss

**Comment by wvangansbeke** [comment]
Hi @wilxy,

I guess you want to visualize the predictions? The predictions are the coefficients of the polynomial.  It should be fairly easy with opencv to draw the polynomials onto the images. Take a look at `cv2.polylines` or `cv2.circles`.

Best, Wouter
