### ISSUE TITLE
Point t in area loss 

### ISSUE THREAD

**Issue by wilxy** [wvangansbeke/LaneDetection_End2End#58]
Hi Wouter @wvangansbeke ,

I have a question when looking at Figure2. The picture is 1280*720. Why do you set point t to 0.7, not 896(1280*0.7)?

Best,
Wilxy

**Comment by wvangansbeke** [comment]
Hi @wilxy,

Point t is set to 0.7 because the grid is already normalized between 0 and 1. 

Best, 
Wouter

**Comment by wilxy** [comment]
Hi Wouter  @wvangansbeke ,

Thank you for your kindly reply. 
I'm not skilled in pytorch. Could you please point out the normalized code to me? 

Best regards,
Wilxy

**Comment by wvangansbeke** [comment]
Hi @wilxy,

The normalization step is extremely easy. Just divide the absolute pixel coordinates (height, width) by the aspect ratio of the image (H, W).

Best,
Wouter
