### ISSUE TITLE
what's the β parameter？

### ISSUE THREAD

**Issue by maxadda** [wvangansbeke/LaneDetection_End2End#6]
Hi , I used the Tusimple dataset to generate the training label (the value of β) according to the description in your paper. There are several questions I would like to ask you:
1. I found that the Y coordinate generated by the pixel after the transformation matrix will produce negative coordinates?
2. Can you share several sets of generated β values?

**Comment by wvangansbeke** [comment]
Hi, 

1. Probably something went wrong, but you can take a look at the code now. I used a fixed homography matrix and transformed the X, Y, Z (homogeneous) coordinates using this projection matrix.

2. You can find the ground truth β values in Labels/Curve_parameters.json with the label "poly_params". (These are valid in a normalized grid between 0 and 1.)

Hope this helps!
