### ISSUE TITLE
Run the code in Bakprojection_Loss in the TuSimple dataset

### ISSUE THREAD

**Issue by YangChen1234567** [wvangansbeke/LaneDetection_End2End#63]
Hello, when I run the code in theBackprojection_Loss directory on the complete dataset of TuSimple, I found that there is no "ground_truth" directory in Tusimple's train set(just a 'clips' and 3 json files). 
![image](https://user-images.githubusercontent.com/44695720/72206392-5a38d900-34c8-11ea-93bf-dbdd85c45f08.png)

However, the command given in your repo includes the "gt_dir" parameter. I am a newcomer in this field, could you please to tell me how to run the code(in backprojection_loss) on the complete dataset of TuSimple? Thank you very much!

**Comment by kingtaewoo** [comment]
so did you solve it? I cannot run this program

**Comment by YangChen1234567** [comment]
no I didn't






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kingtaewoo"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 上午8:44
收件人: "wvangansbeke/LaneDetection_End2End"<LaneDetection_End2End@noreply.github.com&gt;; 
抄送: "940547156"<940547156@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [wvangansbeke/LaneDetection_End2End] Run the code in Bakprojection_Loss in the TuSimple dataset (#63)





 
so did you solve it? I cannot run this program
