### ISSUE TITLE
a problem about tensor

### ISSUE THREAD

**Issue by gy958645199** [wvangansbeke/LaneDetection_End2End#64]
Hi,
Thanks for the code, but when i try the Backprojection_Loss, there is a problem i have no idea.
Below is the bug:
D:\Anaconda\envs\pytorch1.1\python.exe D:/LaneDetection/venv/LaneDetection_End2End-master/Backprojection_Loss/main.py --image_dir /LaneDetection/venv/Tusimple_path/image --gt_dir /LaneDetection/venv/Tusimple_path/gt_image_instance --test_dir /LaneDetection/venv/Tusimple_path --end_to_end True
size train loader is 2901
size valid loader is 725
Flipping images randomly: False
End to end lane detection: True
size test loader:  2782
Init weights in network with [kaiming]
========================================
Args:Namespace(activation_layer='square', activation_net='relu', batch_size=8, channels_in=3, clas=False, clip_grad_norm=0, crop_size=80, cudnn=True, dataset='lane_detection', draw_testset=False, end_to_end=True, evaluate=False, flip_on=False, gamma=0.0, gt_dir='/LaneDetection/venv/Tusimple_path/gt_image_instance', image_dir='/LaneDetection/venv/Tusimple_path/image', json_file='Labels/Curve_parameters.json', layers=18, learning_rate=0.0001, list=[954, 2789], loss_policy='area', lr_decay=False, lr_decay_iters=30, lr_policy=None, mask_percentage=0.3, mod='erfnet', nclasses=2, nepochs=500, niter=50, niter_decay=400, no_cuda=False, no_dropout=False, no_mapping=False, no_ortho=False, no_tb=True, norm='batch', num_train=3626, nworkers=8, optimizer='adam', order=2, pool=True, pretrain_epochs=20, pretrained=False, print_freq=500, reg_ls=0, resize=256, resume='', save_freq=100, save_path='Saved/Mod_erfnet_opt_adam_loss_area_lr_0.0001_batch_8_end2end_True_chol_False_lanes_2_pretrainFalse_clasFalse_mask0.3_flip_onFalse_activation_square', skip_epochs=10, split_percentage=0.2, start_epoch=0, test_dir='/LaneDetection/venv/Tusimple_path', test_mode=False, use_cholesky=False, val_batch_size=8, weight_class=1, weight_decay=0, weight_fit=1, weight_funct='none', weight_init='kaiming', weight_seg=30)
========================================
Init model: 'erfnet'
Number of parameters in model ERFNET is 2.063M

 => Start train set for EPOCH 1
Saving to:  Saved/Mod_erfnet_opt_adam_loss_area_lr_0.0001_batch_8_end2end_True_chol_False_lanes_2_pretrainFalse_clasFalse_mask0.3_flip_onFalse_activation_square
0it [00:00, ?it/s]Traceback (most recent call last):
  File "D:/LaneDetection/venv/LaneDetection_End2End-master/Backprojection_Loss/main.py", line 548, in <module>
    main()
  File "D:/LaneDetection/venv/LaneDetection_End2End-master/Backprojection_Loss/main.py", line 296, in main
    loss_left, x_cal0 = criterion(beta0, gt0, valid_points[:, 0])
  File "D:\Anaconda\envs\pytorch1.1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\LaneDetection\venv\LaneDetection_End2End-master\Backprojection_Loss\Loss_crit.py", line 108, in forward
    diff = params.squeeze(-1) - gt_params
RuntimeError: The size of tensor a (3) must match the size of tensor b (56) at non-singleton dimension 1
0it [00:15, ?it/s]

Do u have any idea about this problem? 
Thank u so much!!

**Comment by brendaav** [comment]
I have the same problem. Is there a solution for this now?

**Comment by wvangansbeke** [comment]
Hi @gy958645199,

I handled this in a previous issue, but it has to do with the different behavior between Pytorch versions. I was not able to reproduce this error, but it seems that the output has a different size than it should be from the error. Maybe set a breakpoint and see where the mismatch starts.

Best,
Wouter

**Comment by kingtaewoo** [comment]
hi, I have same problem. 
so, did you solve it? 
can you tell me how to do it?

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/192106456-c8b484b3-b3b2-4ee0-89f8-b44a581c7ee7.png)

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/192106476-a3eaef1b-e6eb-4087-824b-dccfc3d25fa1.png)

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/192106798-db91a868-79b2-4b53-bd3d-4f22f78cdec2.png)
self.num_points = 56
so  area error
