### ISSUE TITLE
how to use network output

### ISSUE THREAD

**Issue by HaminyG** [wvangansbeke/LaneDetection_End2End#65]
Hi, Thanks for this nice job!!! But I have some issues to understand the output from the network. 

return beta0, beta1, beta2, beta3, masked, self.M, output, line, horizon

So these are your output from model, which parameter that I can use to draw the predicted lane?
Thanks

**Comment by HaminyG** [comment]
Oh, I got the output. But it is really awful, what can I do for solving this problem.
![Capture](https://user-images.githubusercontent.com/43503827/76026809-80458d00-5efd-11ea-8644-fec0848e110f.PNG)

**Comment by Lrrixiang** [comment]
Hi:
    HaminyG,I met the same problem,I have no idea about that,Have you tackled the problem.

**Comment by HaminyG** [comment]
Sorry, i didn't solve it, i change to other network.



发自我的iPhone


------------------ Original ------------------

**Comment by wvangansbeke** [comment]
Hi @HaminyG,

Not sure what the problem is, but it seems there was a similar issue  in #12. I think you made a mistake when doing the homography transformation.

Best,
Wouter
