### ISSUE TITLE
Label quick question

### ISSUE THREAD

**Issue by yoga-0125** [wvangansbeke/LaneDetection_End2End#69]
In the readme.md, you mentioned that you appended the three files and used the index in this json file to name a specific image. However, I cannot find those .json files. All files in the label folder name images as "clip/..." instead of "10.jpg". 

Could you let me know where to find the updated files? Thank you very much.

**Comment by wvangansbeke** [comment]
Hi @yoga-0125,

You need to make sure the order in the json file matches the one used in the dataloading. Feel free to change if you want to use a different folder structure. 

Best, 
Wouter
