### ISSUE TITLE
Curve_parameters.json in Backprojection_Loss is not complete

### ISSUE THREAD

**Issue by yoga-0125** [wvangansbeke/LaneDetection_End2End#71]
The Curve_parameters.json in Backprojection_Loss folder has only 3209 data. Could you upload a complete file with 3626 data?

Thanks a lot.

**Comment by wvangansbeke** [comment]
Hi @yoga-0125,

Indeed, this is supposed to be like that. We consider only the images without lane changes for this setup.
Please check the README and previous issues.

Best,
Wouter
