### ISSUE TITLE
Could you upload any test.py for evaluating the accuracy of predictions?

### ISSUE THREAD

**Issue by yoga-0125** [wvangansbeke/LaneDetection_End2End#74]
Could you upload any test code file for evaluating the accuracy of predictions in test data? 
I only found the training code in folders. 
Thanks a lot.

**Comment by wvangansbeke** [comment]
Hi @yoga-0125,

We might include it later, in a few weeks. We are working on another project at the moment, but I remember that the results for the egolane task are pretty easy to obtain. For multi-lane segmentation, we would like to refer you to the README. We included some tips to get decent results for this setup too.

Best, 
Wouter
