### ISSUE TITLE
Time it takes to run

### ISSUE THREAD

**Issue by eunjiahn1** [wvangansbeke/LaneDetection_End2End#77]
Hi. I'm a college student in South Korea.
i major in computer science, and nowadays i study your paper.
im still running your code for 2 hours.
how long will it take to run all of this code?
thank you.

**Comment by wvangansbeke** [comment]
Hi @eunjiahn1, 

I don't remember the exact time it takes to train, but I'm confident it is more than 2 hours. Probably around 12 hours for a high-end gpu. If you are only interested in the egolanes, the code should work out of the box if you let it run overnight. Multi-lane detection was more difficult to get working. Stability issues are a problem here, so I refer to the readme for more tips.  Hope this helps.

Best,
Wouter
