### ISSUE TITLE
How to get the running result

### ISSUE THREAD

**Issue by Lee-AI-sco** [wvangansbeke/LaneDetection_End2End#78]
Hi:
   The code is only for the training phase you released, but how can I get the running result.Like this.
![image](https://user-images.githubusercontent.com/49769622/86209511-521f4380-bba5-11ea-90e0-c33e964cd34f.png)
   Thanks.

**Comment by wvangansbeke** [comment]
Hi @Lrrixiang,

The code only contains the training part indeed. If you want to visualize this, I suggest you take a look at Opencv. You simply have to draw the predictions onto the image.  I'm not going to release this now, since I don't have time atm.

Best,
Wouter

**Comment by kingtaewoo** [comment]
hello, did you solve this issue? , I want to make result like that.
