### ISSUE TITLE
Is it okay if it's bird's eyes view to understand the thesis?

### ISSUE THREAD

**Issue by kingtaewoo** [wvangansbeke/LaneDetection_End2End#82]
hello. 
I succeeded in training through data from bird's eyes view. but I try to train with backprojection, but it's not working well.
so Is it okay if it's bird's eyes view to understand the thesis? 

What is the paper based on between backprojection and bird's eyes view? 

Thank you always.

**Comment by wvangansbeke** [comment]
Hi @kingtaewoo,

For the paper I only included the birds-eye-view part. The backprojection part was something extra I tried for the people that were interested. For the egolane detection, the code with birds-eye-view should work well. For multi-lane detection, I used additional segmentation ground truth for a stronger supervisory signal. 

Hope this helps.
