### ISSUE TITLE
Test on own data

### ISSUE THREAD

**Issue by damithkawshan** [wvangansbeke/LaneDetection_End2End#83]
how can I test your model on my own data?

**Comment by rrryan2016** [comment]
You can check the issue resolved, including https://github.com/wvangansbeke/LaneDetection_End2End/issues/12 , https://github.com/wvangansbeke/LaneDetection_End2End/issues/35 and https://github.com/wvangansbeke/LaneDetection_End2End/issues/54.

Could anyone provide some well-trained model for just quick inference? :P

**Comment by damithkawshan** [comment]
yeah. issue solved. thanks
